### ISSUE TITLE
make install more portable on Archlinux (don't use aura)

### ISSUE THREAD

**Issue by mkwmms** [mkwmms/ansible-dotstrap-fasd#1]
Ref. [tasks/main.yml:6](https://github.com/mkwmms/ansible-dotstrap-fasd/blob/31c12e9cd2974e1a021b13f6da48687ba506ae26/tasks/main.yml#L6)

```yml
    # TODO make install more portable on Archlinux (don't use aura)
    - name: install fasd
      command: "aura -A {{ name }} --needed --noconfirm"
      when: ansible_distribution == 'Archlinux'
      become: yes

…
```
