### ISSUE TITLE
switch to another archlinux package manager module due to permissions issues

### ISSUE THREAD

**Issue by mkwmms** [mkwmms/ansible-dotstrap-fasd#5]
Ref. [tasks/main.yml:6](https://github.com/mkwmms/ansible-dotstrap-fasd/blob/89078d3b63e6c9f0f19da269e60f9095053d571f/tasks/main.yml#L6)

```yml
    # TODO switch to another archlinux package manager module due to permissions issues
    # see: mkwmms/ansible-github#3
    - name: install fasd
      yaourt: name="{{ name }}"
      when: ansible_distribution == 'Archlinux'
      # become: yes
…
```

**Comment by mkwmms** [comment]
Ref. [tasks/configure.yml:6](https://github.com/mkwmms/ansible-dotstrap-fasd/blob/b58592cae65509ad71f968d5c6c7a825ac79b627/tasks/configure.yml#L6)

```yml
    # TODO switch to another archlinux package manager module due to permissions issues
    # see: mkwmms/ansible-github#3
    - name: package | yaourt
      yaourt: name="{{ fasd_name }}"
      when: ansible_distribution == 'Archlinux'
      # become: yes
…
```

**Comment by mkwmms** [comment]
Ref. [tasks/install.yml:6](https://github.com/mkwmms/ansible-dotstrap-fasd/blob/b58592cae65509ad71f968d5c6c7a825ac79b627/tasks/install.yml#L6)

```yml
    # TODO switch to another archlinux package manager module due to permissions issues
    # see: mkwmms/ansible-github#3
    - name: package | yaourt
      yaourt: name="{{ fasd_name }}"
      when: ansible_distribution == 'Archlinux'
      # become: yes
…
```
